### ISSUE TITLE
QOL changes 

### ISSUE THREAD

**Issue by bensharp1** [pinterest/snappass#102] opened 2019-05-29 11:07 UTC
EDIT to add that the pip package is now out of date since version 1.5.0, https://pypi.org/project/snappass/ still lists the latest as 1.4.1.

On client side we found that there were 3 possible actions that appear unintentional.

1) Secret text is stored in browser text box after pressing "back" after link is generated.
2) Multiple links can be generated when refreshing link generation page.
3) Submitting blank secrets generates unnecessary links.

For now we implemented fixes using javascript on the html files:

For 1) We added `document.getElementById("password").value = "";` to set_password.html

For 2) We added ` if ( window.history.replaceState ) { window.history.replaceState( null, null, window.location.href );` to confirm.html 

For 3) We added `$('#password').bind('input propertychange', function() {
  if ($('#password').val().length == 0) {
    $('#submit').attr("disabled", true);
  } else {
    $('#submit').removeAttr('disabled');
  }` to set_password.html to disable the confirm button if not being used. 

However these will not work if the user disables javascript in browser and would be good to see this resolved in the base application.

**Comment by devinlundberg** [comment] 2019-05-30 16:22
For 1)  autocomplete="off" should prevent this. It looks like we have that property applied to the textarea tag instead of the form tag. Moving it to the right html tag should resolve the issue and is likely a better solution than a javascript based one (since some users could have js disabled as you call out).

For 2) I don't know of a better solution and a javascript solution sounds reasonable (this doesn't actually break anything if javascript is disabled). Many browsers do warn that you are about to resubmit the form for refresh on POSTs and I'm able to reproduce this warning on chrome with snappass so I think this is the least impactful issue you flagged.

For 3) I think a server-side solution to not generate links for empty data might be best here. Should a be a simple if statement. We could also add the `required` property to the form field to prevent this client side.

**Comment by bensharp1** [comment] 2019-05-31 11:28
These all sound good.

I have just moved the autocomplete='off' to the form tag, and that has resolved that issue even with Javascript disabled as you say.

Having both a server-side and client-side solution for 3) would be great.

**Comment by jparise** [comment] 2019-05-31 14:37
@bensharp1 would you mind opening a Pull Request for that `autocomplete="off"` change given that you've successfully verified that approach?

**Comment by nichochar** [comment] 2019-06-10 16:28
Closing this, as these were addressed, merged and deployed in 1.4.2

**Closed by nichochar** 2019-06-10 16:29 UTC
